routes/admin.php
    Route::resource('parking-transaction', 'ParkingTransactionController');

    Route::resource('user-cars', 'UserCarController')->only('create', 'store', 'edit', 'update');

    Route::get('logs', 'AdminCommonController@getLog')->name('getLog');
    Route::any('getAllLogs', 'AdminCommonController@getAllLogs')->name('getAllLogs');

    Route::post('offers/change-status/{type}/{status}', 'OfferController@changeStatus')->name('offers.changeStatus');
    Route::get('offers/edit/{parentName}/{merchanteName}', 'OfferController@edit')->name('offers.edit');
    Route::post('offers/update/{parentName}/{merchanteName}', 'OfferController@update')->name('offers.update');
    Route::any('offers/datatable', 'OfferController@datatable')->name('offers.datatable');
    Route::get('offers/updateExistingOrder', 'OfferController@updateExistingOrder')->name('offers.updateExistingOrder');
    Route::get('offers', 'OfferController@index')->name('offers.index');
    Route::get('offers/update-existing', 'OfferController@updateExisting')->name('offers.updateExisting');

    //Programs
    Route::any('programs/datatable', 'ProgramController@datatable')->name('programs.datatable');
    Route::any('programs/{id}/slots/datatable', 'ProgramSlotController@datatable')->name('programs.slots.datatable');
    Route::get('programs/{id}/slots/export', 'ProgramSlotController@export')->name('programs.slots.export');
    Route::post('programs/{id}/slots/changeStatus', 'ProgramSlotController@changeStatus')->name('programs.slots.changeStatus');
    Route::resource('programs/{id}/slots', 'ProgramSlotController', ['as' => 'programs']);
    Route::post('programs/changeStatus', 'ProgramController@changeStatus')->name('programs.changeStatus');
    Route::resource('programs', 'ProgramController');
    Route::any('book-programs-slots/{id}', 'ProgramController@getSlots')->name('programs.slots.book');
    Route::post('book-programs-confirm', 'ProgramController@cofirmSlotBooking')->name('programs.book.confirm');
    Route::post('cancel-booking-slot', 'ProgramSlotController@cancelSlotBooking')->name('programs.booked-slot.cancel');
    Route::post('release-booking-slot', 'ProgramSlotController@releaseSlotBooking')->name('programs.booked-slot.release');
    Route::post('get-tables-by-type', 'TableController@getTablesByType')->name('tables.get.by.type');
    Route::any('program-report', 'ProgramReportController@index')->name('program.day.report');
    Route::post('program-report-details', 'ProgramReportController@show')->name('program.day.report.details');
    Route::any('program-onsite-collections', 'MajlisBookingController@onsiteIndex')->name('program.onsite.collections');
    Route::post('program-onsite-collection-details', 'MajlisBookingController@onsiteShow')->name('program.onsite.collection.details');
    Route::post('program-change-table', 'ProgramReportController@changeTable')->name('program.change.table');
    Route::post('program-change-table-store', 'ProgramReportController@storeChangedTable')->name('program.changed.table.store');
    Route::post('program-change-date', 'ProgramReportController@changeDate')->name('program.change.date');
    Route::get('program-release-slots', 'ProgramReportController@getReleaseSlots')->name('program.get.release.slots');
    Route::post('program-get-qrcodes', 'ProgramReportController@getQrcodes')->name('program.get.qrcodes');
    Route::get('find-majlis-bookings', 'MajlisBookingController@findBookings')->name('find.majlis.bookings');
    Route::post('majlis-bookings-datatable', 'MajlisBookingController@datatable')->name('majlis.bookings.datatable');
    Route::get('onsite-collections/export', 'MajlisBookingController@export')->name('program.onsite.collections.export');

    Route::get('promocode-update', 'DbUpdateController@promocode')->name('promocode');

    //Season
    Route::get('season/packs/{id}', 'SeasonController@packs')->name('season.packs');
    Route::get('season/offers/{id}', 'SeasonController@offers')->name('season.offers');
    Route::get('season/download/{id}', 'SeasonController@download')->name('season.download');
    Route::get('season/downloadOffer/{id}', 'SeasonController@downloadOffer')->name('season.downloadOffer');
    Route::any('season/packdatatable', 'SeasonController@packdatatable')->name('season.packdatatable');
    Route::any('season/datatable', 'SeasonController@datatable')->name('season.datatable');
    Route::post('season/changeStatus', 'SeasonController@changeStatus')->name('season.changeStatus');
    Route::post('season/changePackActivation', 'SeasonController@changePackActivation')->name('season.changePackActivation');
    Route::resource('season', 'SeasonController');
    Route::get('current-season', 'SeasonController@currentSeason')->name('current-season');
    Route::post('current-season-update/{id}', 'SeasonController@currentSeasonUpdate')->name('current-season-update');

    Route::any('pack-product-config/datatable', 'PackProductConfigController@datatable')->name('pack-product-config.datatable');
    Route::resource('pack-product-config', 'PackProductConfigController');

    Route::resource('fitness-season', 'FitnessSeasonsController');
    Route::any('fitness-season/dt', 'FitnessSeasonsController@datatable')->name('fitness-season.datatable');
    Route::post('fitness-season-status', 'FitnessSeasonsController@publish')->name('fitness-season.fitness-season-status');
    Route::post('post-sortable', 'FitnessSeasonsController@sortable_update')->name('fitness-season.post-sortable');
    Route::get('delete-fitness-season-image/{id}', 'FitnessSeasonsController@delete_fitness_season_image')->name('fitness-season.delete-fitness-season-image');
    Route::get('fitness-tracks/{cat}', 'FitnessTrackController@index')->name('fitness-track.index');
    Route::any('fitness-daily-tracks-dt', 'FitnessTrackController@dailyTracks')->name('fitness.daily-tracks.dt');
    Route::post('fitness-season-images-url', 'FitnessSeasonsController@updateImagesType');
    Route::post('fitness-season-images-setdefault', 'FitnessSeasonsController@setDefaultImage');
    Route::post('fitness-mark-collected-tracks/{type}', 'FitnessTrackController@markAsCollected')->name('fitness.mark.track');
    Route::get('fitness-track-delete', 'FitnessTrackController@getDeletePage')->name('fitness-track-delete');
    Route::get('fitness-track-delete-record', 'FitnessTrackController@deleteRecords')->name('fitness-track-delete-record');

    Route::any('vehicle-plocations-dt', 'VehiclePlocationController@datatable')->name('vehicle-plocations.datatable');
    Route::post('vehicle-plocations-status', 'VehiclePlocationController@changeStatus')->name('vehicle-plocations.status');
    Route::post('vehicle-plocations-sync', 'VehiclePlocationController@syncCount')->name('vpl.sync.count');
    Route::post('clear-user-parkings-cronstatus', 'VehiclePlocationController@clearUserParkingsCronStatus')->name('clear.user.parkings.cronstatus');
    Route::get('parking-area', 'VehiclePlocationController@parkingArea')->name('parking.area');
    Route::post('parking-area', 'VehiclePlocationController@saveParkingArea')->name('parking.area.save');
    Route::get('clear-user-parkings', 'VehiclePlocationController@clearUserParkings')->name('clear.user.parkings');
    Route::resource('vehicle-plocations', 'VehiclePlocationController');
    Route::get('del-vpl-image/{id}', 'VehiclePlocationController@delImage')->name('vpl.delete.image');
    Route::get('vehicle-inside', 'VehiclePlocationController@getVinside')->name('vpl.get.vinside');
    Route::post('vehicle-inside', 'VehiclePlocationController@postVinside')->name('vpl.post.vinside');
    Route::any('parking-services/dt', 'ParkingServicesController@datatable')->name('parking.services.datatable');
    Route::resource('parking-services', 'ParkingServicesController');

    /*Route::any('snw-campaigns/dt', 'SnwCampaignController@datatable')->name('snw-campaigns.datatable');
    Route::resource('snw-campaigns', 'SnwCampaignController');
    Route::post('snw-json-status', 'SnwCampaignController@changeStatus')->name('snw.status');
    Route::any('snw-prizes/dt', 'SnwPrizeController@datatable')->name('snw-prizes.datatable');
    Route::resource('snw-prizes', 'SnwPrizeController');*/
    Route::any('notifications/dt', 'NotificationController@datatable')->name('notifications.datatable');
    Route::resource('notifications', 'NotificationController');


    Route::get('offer-link-update', 'OfferController@offerLinks')->name('offer.links');

    Route::any('offersdelete/datatable', 'OfferDeleteController@datatable')->name('offersdelete.datatable');
    Route::resource('offersdelete', 'OfferDeleteController');

    Route::any('saleforce/datatable', 'SalesForceLogController@datatable')->name('saleforce.datatable');
    Route::resource('saleforce', 'SalesForceLogController');
    Route::get('saleforce-pending', 'SalesForceLogController@pending')->name('saleforce.pending');
    Route::any('cabana-days/datatable', 'CabanaController@datatable')->name('cabana-days.datatable');
    Route::post('cabana-days/changeStatus', 'CabanaController@changeStatus')->name('cabana-days.changeStatus');
    Route::resource('cabana-days', 'CabanaController');
    Route::any('cabana-products/datatable', 'CabanaProductController@datatable')->name('cabana-products.datatable');
    Route::post('cabana-products/changeStatus', 'CabanaProductController@changeStatus')->name('cabana-products.changeStatus');
    Route::resource('cabana-products', 'CabanaProductController');

    Route::get('fifa-matches/export', 'FifaMatchesController@export')->name('fifa-matches.export');
    Route::any('fifa-matches/datatable', 'FifaMatchesController@datatable')->name('fifa-matches.datatable');
    Route::resource('fifa-matches', 'FifaMatchesController');


    Route::get('debug-booking/order_confirmed', 'DebugBookingController@index')->name('debug-booking');

routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */
 Route::get('/activate', function() {
     return Redirect::to('en');
 });

Route::get('/', function() {
    return Redirect::to('en',301);
});

Route::get('testMails', ['as' => 'test-mails', 'uses' => 'Web\TestMailController@index']);
Route::get('testPass', ['as' => 'test-mails', 'uses' => 'Web\TestMailController@testPass']);

Route::get('test-exp', ['as' => 'test-mails', 'uses' => 'Web\TestMailController@export']);

Route::group(['prefix' => '{lang?}', 'middleware' => ['web', 'setlocale'], 'where' => ['lang' => 'en|ar']], function () {
    Route::get('/', 'Web\HomeController@index')->name('home');
    Route::post('check-activation-code', 'Web\HomeController@checkActivationCode')->name('check.activationCode');
    Route::post('generate-otp', 'Web\HomeController@generateOtp')->name('generateOtp');
    Route::post('get-emirates', 'Web\HomeController@getEmirates')->name('get.emirates');
    Route::post('get-plate-prefix', 'Web\HomeController@getPlatePrefix')->name('get.platePrefix');
    Route::post('activate-pack', 'Web\HomeController@activatePack')->name('pack.activate');
    Route::get('my-activated-pack/{id}', 'Web\HomeController@myActivatedPack')->name('my.activated.pack');
    Route::post('pack-offers', 'Web\HomeController@packOffers')->name('pack.offers');

    Route::get('offer-download/{id}', 'Web\HomeController@packOfferDownload')->name('pack-offer-download');
    Route::get('offer-hide/{id}', 'Web\HomeController@hideOffer')->name('hideOffer');

    Route::get('test', 'Web\HomeController@test')->name('pack.offers-test');

    Route::get('generate-qrcode', 'Web\HomeController@generateTestQrCode')->name('pack.qr-test');

    Route::post('load-popup-content', 'Web\HomeController@load_popup_content')->name('load-popup-content');
    Route::post('manage-car-detail', 'Web\HomeController@manage_car_detail')->name('manage-car-detail');

    Route::post('add-more-car', 'Web\HomeController@addMoreCar')->name('addMoreCar');


    Route::get('testSaleforce', 'Web\HomeController@testSaleforce')->name('testSaleforce');
    Route::get('testSaleforceUrl', 'Web\HomeController@testSaleforceUrl')->name('testSaleforceUrl');

});

resources/views/admin/pack_product/create.blade.php
@extends('adminlte::page')

@section('title', 'Add Product ID')

@section('content_header')
<h1> Add Product ID</h1>
@stop

@section('content')
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="box box-success">
            <div class="box-header">
                <div class="box-tools">
                    <a href="{{route('admin.pack-product-config.index')}}" class="btn btn-sm btn-default">Back</a>
                </div>
            </div>
           
            {{ Form::open(array('url' => 'admin/pack-product-config')) }}
            <div class="box-body">
                @include("admin.pack_product.form")
              
                <div class="form-group">
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        {{ Form::submit('Add', array('class' => 'btn btn-primary')) }}
                    </div>
                </div>
            </div>
            {{ Form::close() }}

                
        </div>
    </div>
</div>
@stop

resources/views/admin/pack_product/form.blade.php
<div class="form-group {{ $errors->has('product') ? 'has-error' : '' }}">
    {{ Form::label('product', 'Product') }}
    {{ Form::text('product', null, array('class' => 'form-control', 'required'=>"required")) }}
     {!! $errors->first('product','<p class="text-danger"><strong>:message</strong></p>') !!}
</div>

<div class="form-group {{ $errors->has('product_name') ? 'has-error' : '' }}">
    {{ Form::label('product_name', 'Product Name') }}
    {{ Form::text('product_name', null, array('class' => 'form-control', 'required'=>"required")) }}
     {!! $errors->first('product_name','<p class="text-danger"><strong>:message</strong></p>') !!}
</div>

<div class="form-group {{ $errors->has('product_id') ? 'has-error' : '' }}">
    {{ Form::label('product_id', 'Product ID') }}
    {{ Form::text('product_id', null, array('class' => 'form-control', 'required'=>"required")) }}
     {!! $errors->first('product_id','<p class="text-danger"><strong>:message</strong></p>') !!}
</div>
<div class="form-group {{ $errors->has('slug') ? 'has-error' : '' }}">
	{{ Form::label('slug', 'Slug') }}
    {{ Form::select('slug', $pack_product_slug,null, array('class' => 'form-control', 'required'=>"required")) }}
     {!! $errors->first('slug','<p class="text-danger"><strong>:message</strong></p>') !!}
</div>                      

resources/views/admin/pack_product/index.blade.php
@extends('adminlte::page')

@section('title', 'Product Id')

@section('content_header')
<h1> Seasons</h1>
@stop

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="box box-success">
            <div class="box-header">
                <h3>&nbsp;</h3>
                <div class="box-tools">
                    <a href="{{route('admin.pack-product-config.create')}}" class="btn btn-sm btn-primary">Create Product Id</a>
                </div>

            </div>
            <div class="box-body">
            
                
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover" id="list-table">

                        <thead>
                            <tr>
                                <th>Slug</th>
                                <th>Product</th>
                                <th>Product Name</th>
                                <th>Product ID</th>                               
                                <th></th>
                            </tr>
                        </thead>


                    </table>
                </div>

            </div>
        </div>
    </div>
</div>
@stop
@section("css")

<link rel="stylesheet" href="{{asset('css/bootstrap4-toggle.min.css')}}">
@stop
@section('js')
<script src="{{asset('js/bootstrap4-toggle.min.js')}}"></script>
<script type='text/javascript'>
    $(function () {
        
        oTable = $('#list-table').DataTable({
            processing: true,
            serverSide: true,
            //autoWidth: false,
            ordering: false,
            ajax: {
                url: '{!! route('admin.pack-product-config.datatable') !!}',
                type: 'post',
                headers: {'X-CSRF-TOKEN': '{{ csrf_token() }}'},
                 data: function ( d ) {
                     
                },
            },
           
            columns: [
               
                {data: 'slug', name: 'slug'},
                {data: 'product', name: 'product'},
                {data: 'product_name', name: 'product_name'},
                {data: 'product_id', name: 'product_id'},
                
                {data: 'actions', name: 'actions', orderable: false, searchable: false}
            ],
           
        });
        

        $('#list-table').on('click', '.destroy', function (e) {
            e.preventDefault();
            var href = $(this).attr('href');

            swal({
                title: "{{ trans('myadmin.confirm-delete') }}",
                text: "Once deleted, you will not be able to recover this file!",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                    .then((willDelete) => {
                        if (willDelete) {
                            $.ajax({
                                url: href,
                                method: 'DELETE',
                                headers: {'X-CSRF-TOKEN': '{{ csrf_token() }}'},
                                beforeSend: function () {
                                    Pace.restart();//Pace.start();
                                },
                                success: function () {
                                    oTable.ajax.reload();
                                    swal("Done!", "User successfully deleted.", "success");
                                },
                                error: function (xhr, ajaxOptions, thrownError) {
                                    swal("Error deleting!", "Please try again", "error");
                                },
                                complete: function () {
                                    Pace.stop();
                                }
                            });
                        } else {
                            return true;
                        }
                    });
        });
      

    });

</script>    
@stop