routes/admin.php
<?php

/*
  |--------------------------------------------------------------------------
  | Admin Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register Admin routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */
Route::get('/', function () {
    return Redirect::to('admin/login');
});
Route::group(['namespace' => 'Auth', 'as' => 'admin.'], function () {
    Route::get('/login', 'AdminLoginController@showLoginForm')->name('login');
    Route::post('/login', 'AdminLoginController@login')->name('login.submit');
    Route::post('/logout', 'AdminLoginController@logout')->name('logout');

    //admin password reset routes
    Route::post('/password/email', 'AdminForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/password/reset', 'AdminForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/password/reset', 'AdminResetPasswordController@reset');
    Route::get('/password/reset/{token}', 'AdminResetPasswordController@showResetForm')->name('password.reset');
});

Route::group(['middleware' => 'isAdmin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {
    Route::get('/', 'HomeController@index')->name('dashboard');
    Route::resource('users', 'AdminController');
    Route::any('users/dt', 'AdminController@datatable')->name('users.datatable');
    Route::get('user/profile', 'AdminController@profile')->name('user.profile');
    Route::post('user/profile', 'AdminController@profilePost')->name('user.profile.post');
    Route::post('user/profile/avatardelete', 'AdminController@avatarDelete')->name('user.avatardelete');

    Route::resource('roles', 'RoleController');
    Route::resource('permissions', 'PermissionController');

    //Slot
    Route::resource('slots', 'SlotController');
    Route::any('slots/datatable', 'SlotController@datatable')->name('slots.datatable');
    Route::post('slots/changeStatus', 'SlotController@changeStatus')->name('slots.changeStatus');

    //Table
    Route::resource('tables', 'TableController');
    Route::any('tables/datatable', 'TableController@datatable')->name('tables.datatable');
    Route::post('tables/changeStatus', 'TableController@changeStatus')->name('tables.changeStatus');

    //Import
    Route::get('import/{type}', 'ImportController@import')->name('import');
    Route::post('import-packs}', 'ImportController@importPacks')->name('import.packs');
    Route::post('import-wonderpass}', 'ImportController@importWonderpass')->name('import.wonderpass');
    Route::post('import-offers}', 'ImportController@importOffers')->name('import.offers');

    //shopcart transaction data
    Route::resource('shop-cart-transaction', 'ShopCartTransactionController');
    Route::any('shop-cart-transaction/dt', 'ShopCartTransactionController@datatable')->name('shop-cart-transaction.datatable');

    // Route::get('shop-cart-transaction-export', 'ShopCartTransactionController@export');

    //shopcart transaction data
    Route::get('shop-cart-transaction-cc', 'ShopCartTransactionController@getCallCenterData');
    Route::any('shop-cart-transaction-cc/dt', 'ShopCartTransactionController@getCCDatatable')->name('shop-cart-transaction-cc.datatable');

    Route::get('shop-cart-transaction-old', 'ShopCartTransactionController@getArchieve');
    Route::any('shop-cart-transaction-old/dt', 'ShopCartTransactionController@arhieveDatatable')->name('shop-cart-transaction-old.datatable');

    /**
     * History Transactions
     */
    //shopcart transaction data
    Route::resource('shop-cart-history-transaction', 'ShopCartTransactionHistoryController');
    Route::any('shop-cart-history-transaction/dt', 'ShopCartTransactionHistoryController@datatable')->name('shop-cart-history-transaction.datatable');

    // Route::get('shop-cart-transaction-export', 'ShopCartTransactionHistoryController@export');

    //shopcart transaction data
    Route::get('shop-cart-history-transaction-cc', 'ShopCartTransactionHistoryController@getCallCenterData');
    Route::any('shop-cart-history-transaction-cc/dt', 'ShopCartTransactionHistoryController@getCCDatatable')->name('shop-cart-history-transaction-cc.datatable');

    Route::get('shop-cart-history-transaction-old', 'ShopCartTransactionHistoryController@getArchieve');
    Route::any('shop-cart-history-transaction-old/dt', 'ShopCartTransactionHistoryController@arhieveDatatable')->name('shop-cart-history-transaction-old.datatable');
    /**
     * End History Transactions
     */

    Route::get('car-plate-info', 'CarPlateInfoController@index')->name('car-plate-info');
    Route::any('car-plate-info/dt', 'CarPlateInfoController@datatable')->name('car-plate-info.datatable');

    Route::post('car-plate-sync-designa', 'CarPlateInfoController@syncDesigna')->name('car-info.sync.designa');

    Route::post('load-popup-content', 'AdminCommonController@load_popup_content')->name('load-popup-content');
    Route::post('show-audit-log/{type}', 'AdminCommonController@show_audit_logs')->name('show-audit-log');

    Route::any('packs/datatable', 'PackController@datatable')->name('packs.datatable');
    Route::post('packs/activate', 'PackController@activate')->name('packs.activate');
    Route::post('packs/syncDrupal', 'PackController@syncDrupal')->name('packs.syncDrupal');
    Route::post('packs/syncAllDrupal', 'PackController@syncAllDrupal')->name('packs.syncAllDrupal');
    Route::post('packs-sync-designa', 'PackController@syncDesigna')->name('packs.sync.designa');
    Route::get('packs/edit-user/{id}', 'PackController@editUser')->name('packs.editUser');
    Route::post('packs/save-user/{id}', 'PackController@saveUser')->name('packs.saveUser');
    Route::get('packs/remove-user/{id}', 'PackController@removeUser')->name('packs.removeUser');
    Route::get('packs/export', 'PackController@export')->name('packs.export');
    Route::get('packs/updateTestPacks', 'PackController@updateTestPacks')->name('packs.updateTestPacks');
    Route::get('packs/removeOffers/{id}', 'PackController@removeOffers')->name('packs.removeOffers');
    Route::get('packs/blockUser/{id}', 'PackController@blockUser')->name('packs.blockUser');
    Route::get('packs/removetestOffers/{from}/{to}', 'PackController@removetestOffers')->name('packs.removetestOffers');
    Route::get('packs/rm-urs', 'PackController@removeAllSeasonUsers')->name('packs.removeAllUsers');

    Route::get('packs/updateUserCars', 'PackController@updateUserCars')->name('packs.updateUserCars');

    Route::resource('packs', 'PackController');
    Route::resource('dynamic-texts', 'DynamicTextController');
    Route::resource('email-templates', 'EmailTemplateController');
    Route::resource('removed-plate-prefixes', 'RemovedPlatePrefixController');

    Route::get('plate-prefix', 'ApiConfigurationController@platePrefix')->name('platePrefix');
    Route::get('plate-prefix/{type}/{code}/edit', 'ApiConfigurationController@platePrefixEdit')->name('platePrefixEdit');
    Route::post('plate-prefix/{type}/{code}/update', 'ApiConfigurationController@platePrefixUpdate')->name('platePrefixUpdate');
    Route::resource('configuration', 'ApiConfigurationController');

    Route::any('parking-transaction/dt', 'ParkingTransactionController@datatable')->name('parking.transaction.datatable');
    Route::resource('parking-transaction', 'ParkingTransactionController');

    Route::resource('user-cars', 'UserCarController')->only('create', 'store', 'edit', 'update');

    Route::get('logs', 'AdminCommonController@getLog')->name('getLog');
    Route::any('getAllLogs', 'AdminCommonController@getAllLogs')->name('getAllLogs');

    Route::post('offers/change-status/{type}/{status}', 'OfferController@changeStatus')->name('offers.changeStatus');
    Route::get('offers/edit/{parentName}/{merchanteName}', 'OfferController@edit')->name('offers.edit');
    Route::post('offers/update/{parentName}/{merchanteName}', 'OfferController@update')->name('offers.update');
    Route::any('offers/datatable', 'OfferController@datatable')->name('offers.datatable');
    Route::get('offers/updateExistingOrder', 'OfferController@updateExistingOrder')->name('offers.updateExistingOrder');
    Route::get('offers', 'OfferController@index')->name('offers.index');
    Route::get('offers/update-existing', 'OfferController@updateExisting')->name('offers.updateExisting');

    //Programs
    Route::any('programs/datatable', 'ProgramController@datatable')->name('programs.datatable');
    Route::any('programs/{id}/slots/datatable', 'ProgramSlotController@datatable')->name('programs.slots.datatable');
    Route::get('programs/{id}/slots/export', 'ProgramSlotController@export')->name('programs.slots.export');
    Route::post('programs/{id}/slots/changeStatus', 'ProgramSlotController@changeStatus')->name('programs.slots.changeStatus');
    Route::resource('programs/{id}/slots', 'ProgramSlotController', ['as' => 'programs']);
    Route::post('programs/changeStatus', 'ProgramController@changeStatus')->name('programs.changeStatus');
    Route::resource('programs', 'ProgramController');
    Route::any('book-programs-slots/{id}', 'ProgramController@getSlots')->name('programs.slots.book');
    Route::post('book-programs-confirm', 'ProgramController@cofirmSlotBooking')->name('programs.book.confirm');
    Route::post('cancel-booking-slot', 'ProgramSlotController@cancelSlotBooking')->name('programs.booked-slot.cancel');
    Route::post('release-booking-slot', 'ProgramSlotController@releaseSlotBooking')->name('programs.booked-slot.release');
    Route::post('get-tables-by-type', 'TableController@getTablesByType')->name('tables.get.by.type');
    Route::any('program-report', 'ProgramReportController@index')->name('program.day.report');
    Route::post('program-report-details', 'ProgramReportController@show')->name('program.day.report.details');

routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */
 Route::get('/activate', function() {
     return Redirect::to('en');
 });

Route::get('/', function() {
    return Redirect::to('en',301);
});

Route::get('testMails', ['as' => 'test-mails', 'uses' => 'Web\TestMailController@index']);
Route::get('testPass', ['as' => 'test-mails', 'uses' => 'Web\TestMailController@testPass']);

Route::get('test-exp', ['as' => 'test-mails', 'uses' => 'Web\TestMailController@export']);

Route::group(['prefix' => '{lang?}', 'middleware' => ['web', 'setlocale'], 'where' => ['lang' => 'en|ar']], function () {
    Route::get('/', 'Web\HomeController@index')->name('home');
    Route::post('check-activation-code', 'Web\HomeController@checkActivationCode')->name('check.activationCode');
    Route::post('generate-otp', 'Web\HomeController@generateOtp')->name('generateOtp');
    Route::post('get-emirates', 'Web\HomeController@getEmirates')->name('get.emirates');
    Route::post('get-plate-prefix', 'Web\HomeController@getPlatePrefix')->name('get.platePrefix');
    Route::post('activate-pack', 'Web\HomeController@activatePack')->name('pack.activate');
    Route::get('my-activated-pack/{id}', 'Web\HomeController@myActivatedPack')->name('my.activated.pack');
    Route::post('pack-offers', 'Web\HomeController@packOffers')->name('pack.offers');

    Route::get('offer-download/{id}', 'Web\HomeController@packOfferDownload')->name('pack-offer-download');
    Route::get('offer-hide/{id}', 'Web\HomeController@hideOffer')->name('hideOffer');

    Route::get('test', 'Web\HomeController@test')->name('pack.offers-test');

    Route::get('generate-qrcode', 'Web\HomeController@generateTestQrCode')->name('pack.qr-test');

    Route::post('load-popup-content', 'Web\HomeController@load_popup_content')->name('load-popup-content');
    Route::post('manage-car-detail', 'Web\HomeController@manage_car_detail')->name('manage-car-detail');

    Route::post('add-more-car', 'Web\HomeController@addMoreCar')->name('addMoreCar');


    Route::get('testSaleforce', 'Web\HomeController@testSaleforce')->name('testSaleforce');
    Route::get('testSaleforceUrl', 'Web\HomeController@testSaleforceUrl')->name('testSaleforceUrl');

});

app/Admin.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;
use App\Notifications\AdminResetPasswordNotification;
use Illuminate\Database\Eloquent\SoftDeletes;

class Admin extends Authenticatable {

    use Notifiable;
    use HasRoles;
    use SoftDeletes;

    protected $guard = 'admin';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'admin_id', 'name', 'email', 'password', 'status', 'type', 'last_login'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function setPasswordAttribute($password) {
        $this->attributes['password'] = bcrypt($password);
    }

    /**
     * Check if current user has an avatar
     *
     * @return string|false
     */
    public function getAvatarPathAttribute() {
        return public_path('images/avatars/' . md5($this->id . $this->created_at) . '.jpg');
    }

    /**
     * Return current user avatar uri
     *
     * @return string
     */
    public function getAvatarUrlAttribute() {
        if (is_file($this->avatar_path)) {
            $ts = filemtime($this->avatar_path);
            return asset('images/avatars/' . md5($this->id . $this->created_at) . '.jpg?t=' . $ts);
        }
        return asset("/images/default_user.png");
    }

    public function sendPasswordResetNotification($token) {
        $this->notify(new AdminResetPasswordNotification($token));
    }

}

resources/views/admin/tables/create.blade.php
@extends('adminlte::page')

@section('title', 'Add new Tables')

@section('content_header')
<h1><i class='fa fa-user-plus'></i> Add Table</h1>
@stop

@section('content')
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="box box-primary">
            <div class="box-header with-border">
                <a href="{{ url('/admin/tables') }}" title="Back"><button class="btn btn-warning btn-xs"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
            </div>
            <div class="box-body">

                {{ Form::open(array('url' => 'admin/tables')) }}

                <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                    {{ Form::label('name', 'Name') }}
                    {{ Form::text('name', '', array('class' => 'form-control')) }}
                    {!! $errors->first('name','<p class="text-danger"><strong>:message</strong></p>') !!}
                </div>

                <div class="form-group {{ $errors->has('type') ? 'has-error' : '' }}">
                    {{ Form::label('type', 'Type') }}
                   <select class="form-control" name="type" id="type">
                        @if(!empty($types))
                            @foreach($types as $key=>$em)
                                <option value="{{$key}}" >{{$em}} </option>
                            @endforeach
                        @endif
                    </select>
                    {!! $errors->first('type','<p class="text-danger"><strong>:message</strong></p>') !!}
                </div>

                <div class="form-group {{ $errors->has('smoking_status') ? 'has-error' : '' }}">
                    {{ Form::label('smoking_status', 'Smoking status') }}
                   <select class="form-control" name="smoking_status" id="smoking_status">
                       
                        <option value="2" >No</option>
                        <option value="1" >Yes</option>
                           
                    </select>
                    {!! $errors->first('smoking_status','<p class="text-danger"><strong>:message</strong></p>') !!}
                </div>
                <?php $seat_types = config('globalconstants.seat_types'); ?>
                <div class="form-group {{ $errors->has('seat_type') ? 'has-error' : '' }}">
                    {{ Form::label('seat_type', 'Seat type') }}
                   <select class="form-control" name="seat_type" id="seat_type">
                       
                        @if(!empty($seat_types))
                            @foreach($seat_types as $key=>$em)
                                <option value="{{$key}}" >{{$em}} </option>
                            @endforeach
                        @endif
                           
                    </select>
                    {!! $errors->first('seat_type','<p class="text-danger"><strong>:message</strong></p>') !!}
                </div>
              <div class="form-group {{ $errors->has('table_number') ? 'has-error' : '' }}">
                    {{ Form::label('table_number', 'Table No') }}
                    {{ Form::number('table_number', '', array('class' => 'form-control allow_numeric')) }}
                    {!! $errors->first('table_number','<p class="text-danger"><strong>:message</strong></p>') !!}
                </div>
                <div class="form-group {{ $errors->has('admin_only') ? 'has-error' : '' }}">
                    {{ Form::checkbox('admin_only',  null,  null, ['class'=>'minimal-red'] ) }}
                    {{ Form::label('admin_only', 'Allow Booking for Admin only') }}
                </div>

                {{ Form::submit('Add', array('class' => 'btn btn-primary')) }}

                {{ Form::close() }}

            </div>
        </div>
    </div>
</div>
@stop
@section('js')
<script>
 $(document).ready(function() {
        $('.allow_numeric').keypress(function (event) {
            return isNumber(event, this)
        });
    });

     // THE SCRIPT THAT CHECKS IF THE KEY PRESSED IS A NUMERIC OR DECIMAL VALUE.
    function isNumber(evt, element) {

        var charCode = (evt.which) ? evt.which : event.keyCode

        if (
            (charCode != 45 || $(element).val().indexOf('-') != -1) &&      // Check minus and only once.
            (charCode != 46 || $(element).val().indexOf('.') != -1) &&      // Check dot and only once.
            (charCode < 48 || charCode > 57))
            return false;

        return true;
    }
</script>
@endsection

resources/views/admin/tables/index.blade.php
@extends('adminlte::page')

@section('title', 'Tables')

@section('content_header')
<h1><i class="fa fa-users"></i> Tables</h1>
@stop

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="box box-success">
            <div class="box-header">
                <a href="{{ route('admin.tables.create') }}" class="btn btn-success btn-sm">Add Table</a>
            </div>
            <div class="box-body">
                
                <div class="row">
                    <div class="col-md-2">
                        <div class="form-group">
                            {{ Form::label('seat_type', 'Seat Type') }}
                            {!! Form::select('seat_type', [0=>'-Any-',2=>'2 Seater',4=>'4 Seater', 6=>'6 Seater'],null, ['class' => 'form-control', 'id' => 'seat_type']) !!}
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            {{ Form::label('type', 'Table Type') }}
                            {!! Form::select('type', [''=>'-Any-']+$types,null, ['class' => 'form-control', 'id' => 'type']) !!}
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            {{ Form::label('smoking_status', 'Smoke Type') }}
                            {!! Form::select('smoking_status', [0=>'-Any-',1=>'Smoking', 2=>'Non Smoking'],null, ['class' => 'form-control', 'id' => 'smoking_status']) !!}
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label for="start_date">&nbsp</label>
                            <button class="btn btn-sm btn-primary form-control filter">Filter</button>
                        </div>
                    </div>
                </div>

                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover" id="users-table">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Seat Type</th>
                                <th>Table No</th>
                                <th>Type</th>
                                <th>Smoking Type</th>                               
                                <th>Status</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@stop
@section("css")

<link rel="stylesheet" href="{{asset('css/bootstrap4-toggle.min.css')}}">
@stop
@section('js')
<script src="{{asset('js/bootstrap4-toggle.min.js')}}"></script>
<script src="{{asset('vendor/adminlte/plugins/iCheck/icheck.min.js')}}"></script>
<script type='text/javascript'>
$(function () {
    oTable = $('#users-table').DataTable({
        processing: true,
        serverSide: true,
        //autoWidth: false,
         ordering: false,
         pageLength: 50,
        ajax: {
            url: "{!! route('admin.tables.datatable') !!}",
            type: 'post',
            headers: {'X-CSRF-TOKEN': '{{ csrf_token() }}'},
            data: function (d) {
                d.seat_type = $('#seat_type').val();
                d.type = $('#type').val();
                d.smoking_status = $('#smoking_status').val();
            }
        },
        columns: [
            {data: 'name', name: 'name'},
            {data: 'seat_type', name: 'seat_type'},
            {data: 'table_number', name: 'table_number'},
            {data: 'type', name: 'type'},
            {data: 'smoking_status', name: 'smoking_status', searchable: false},            
            {data: 'status', name: 'status', orderable: false, searchable: false},
            {data: 'actions', name: 'actions', orderable: false, searchable: false}
        ],
        fnDrawCallback: function () {
            $(".bsSwitch").bootstrapToggle({
                size: "sm",
                onstyle: "success",
                offstyle: "danger",
                on: 'Enabled',
                off: 'Disabled'
            });
        }
    });
    $(document).on("click", "button.filter", function () {
        oTable.ajax.reload();
    });
     $(document).on('change', '.bsSwitch', function () {
            $.ajax({
                url: '{!! route('admin.tables.changeStatus') !!}',
                dataType: 'json',
               
                cache: false,
                method: 'POST',
                data : { id : $(this).data('id')},
                headers: {'X-CSRF-TOKEN': '{{ csrf_token() }}'},
                beforeSend: function () {
                   
                },
                success: function (response) {
                    oTable.draw();
                },
                error: function (response) {
                    
                },
                complete: function () {
                    
                }
            });
       });
});
</script>    
@stop

resources/views/admin/tables/profile.blade.php
@extends('adminlte::page')

@section('title', 'My Profile')

@section('content_header')
<h1><i class='fa fa-user'></i> My Profile</h1>
@stop

@section('content')
    {{ Form::open(['route' => ['admin.user.profile'], 'method' => 'post', 'autocomplete' => 'off', 'files' => true]) }}
        <div class="row">
            <div class="col-sm-12 mbl">
                <span class="btn-group pull-right">
                    <button type="submit" class="btn btn-primary">Save</button>
                </span>
            </div>
        </div>
    <br style="clear: both;">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-5 col-lg-5">
                <div class="info-box">
                    <span class="info-box-icon" style="line-height: normal">
                        <img src="{{ $user->avatar_url }}" class="avatar" alt="avatar"/>
                    </span>
                    <div class="info-box-content">
                        <span class="info-box-text">
                            <p class="mbn"><strong class="h3">{{ $user->name  }}</strong></p>
                            <p class="">{{ $user->roles()->pluck('name')->implode(' ') }}</p>
                        </span>
                        <span class="info-box-more">
                            <p class="mbn text-muted">
                                {{ trans('myadmin.profile.subscribedsince', [
                                    'date' => $user->created_at->format(trans('date.lFdY')),
                                    'since' => $user->created_at->diffForHumans()]) }}
                            </p>
                        </span>
                    </div>
                </div>
                <div class="box box-info">
                    <div class="box-header">
                        @if(is_file($user->avatar_path))
                        <span class="pull-right">
                            <button class="btn btn-xs btn-default" id="remove_avatar">
                                {{ trans('myadmin.profile.delavatar') }}
                            </button>
                        </span>
                        @endif
                        <h3 class="box-title">{{ trans('myadmin.profile.avatar') }}</h3>
                    </div>
                    <div class="box-body">
                        <div class="form-group {{ $errors->has('avatar') ? 'has-error' : '' }}">
                            {!! Form::file('avatar', ['id' => 'avatar']) !!}
                            {!! $errors->first('avatar','<p class="text-danger"><strong>:message</strong></p>') !!}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-7 col-lg-7">
                <div class="box box-primary">
                    <div class="box-header">
                        <h3 class="box-title">Informations</h3>
                    </div>
                    <div class="box-body">
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                                <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                                    {{ Form::label('name', 'Name') }}
                                    {{ Form::text('name', old('name', $user->name), ['class' => 'form-control', 'autofocus']) }}
                                    {!! $errors->first('name','<p class="text-danger"><strong>:message</strong></p>') !!}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                                <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                                    {{ Form::label('email', 'Email') }}
                                    {{ Form::text('email', old('email', $user->email), ['class' => 'form-control']) }}
                                    {!! $errors->first('email','<p class="text-danger"><strong>:message</strong></p>') !!}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                                <div class="form-group {{ $errors->has('password') ? 'has-error' : '' }}">
                                    {{ Form::label('password', 'Password') }}
                                    {{ Form::password('password', ['class' => 'form-control']) }}
                                    {!! $errors->first('password','<p class="text-danger"><strong>:message</strong></p>') !!}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                                <div class="form-group {{ $errors->has('password_confirmation') ? 'has-error' : '' }}">
                                    {{ Form::label('password_confirmation', 'Confirm Password') }}
                                    {{ Form::password('password_confirmation', ['class' => 'form-control']) }}
                                    {!! $errors->first('password_confirmation','<p class="text-danger"><strong>:message</strong></p>') !!}
                                </div>
                            </div>                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {{ Form::close() }}
@stop

@section('css')
<link rel="stylesheet" href="{!! asset('vendor/adminlte/plugins/bootstrap-fileinput/css/fileinput.min.css') !!}">
@stop

@section('js')
<script src="{!! asset('vendor/adminlte/plugins/bootstrap-fileinput/js/fileinput.min.js') !!}"></script>
<script>
    $('#avatar').fileinput({
        showUpload: false,
        uploadAsync: false
    });

    $('#remove_avatar').on('click', function(e){
        e.preventDefault();

        bootbox.confirm("{{ trans('myadmin.profile.confirmdelavatar') }}", function(e){
            if(e === false) return;

            $.ajax({
                url: '{{ route('admin.user.avatardelete') }}',
                type: 'post',
                headers: {'X-CSRF-TOKEN': '{{ csrf_token() }}'},
                cache: false,
                success: function(res) {
                    $('.avatar').attr('src', "{{ asset('/images/default_user.png') }}");
                    growl("{{ trans('myadmin.profile.successdelavatar') }}", "success");
                    $('#remove_avatar').remove();
                }
            });
        })
    });

</script>
@stop