routes/admin.php
    Route::get('shop-cart-transaction-old', 'ShopCartTransactionController@getArchieve');
    Route::any('shop-cart-transaction-old/dt', 'ShopCartTransactionController@arhieveDatatable')->name('shop-cart-transaction-old.datatable');

    /**
     * History Transactions
     */
    //shopcart transaction data
    Route::resource('shop-cart-history-transaction', 'ShopCartTransactionHistoryController');
    Route::any('shop-cart-history-transaction/dt', 'ShopCartTransactionHistoryController@datatable')->name('shop-cart-history-transaction.datatable');

    // Route::get('shop-cart-transaction-export', 'ShopCartTransactionHistoryController@export');

    //shopcart transaction data
    Route::get('shop-cart-history-transaction-cc', 'ShopCartTransactionHistoryController@getCallCenterData');
    Route::any('shop-cart-history-transaction-cc/dt', 'ShopCartTransactionHistoryController@getCCDatatable')->name('shop-cart-history-transaction-cc.datatable');

    Route::get('shop-cart-history-transaction-old', 'ShopCartTransactionHistoryController@getArchieve');
    Route::any('shop-cart-history-transaction-old/dt', 'ShopCartTransactionHistoryController@arhieveDatatable')->name('shop-cart-history-transaction-old.datatable');
    /**
     * End History Transactions
     */

    Route::get('car-plate-info', 'CarPlateInfoController@index')->name('car-plate-info');
    Route::any('car-plate-info/dt', 'CarPlateInfoController@datatable')->name('car-plate-info.datatable');

    Route::post('car-plate-sync-designa', 'CarPlateInfoController@syncDesigna')->name('car-info.sync.designa');

    Route::post('load-popup-content', 'AdminCommonController@load_popup_content')->name('load-popup-content');
    Route::post('show-audit-log/{type}', 'AdminCommonController@show_audit_logs')->name('show-audit-log');

    Route::any('packs/datatable', 'PackController@datatable')->name('packs.datatable');
    Route::post('packs/activate', 'PackController@activate')->name('packs.activate');
    Route::post('packs/syncDrupal', 'PackController@syncDrupal')->name('packs.syncDrupal');
    Route::post('packs/syncAllDrupal', 'PackController@syncAllDrupal')->name('packs.syncAllDrupal');
    Route::post('packs-sync-designa', 'PackController@syncDesigna')->name('packs.sync.designa');
    Route::get('packs/edit-user/{id}', 'PackController@editUser')->name('packs.editUser');
    Route::post('packs/save-user/{id}', 'PackController@saveUser')->name('packs.saveUser');
    Route::get('packs/remove-user/{id}', 'PackController@removeUser')->name('packs.removeUser');
    Route::get('packs/export', 'PackController@export')->name('packs.export');
    Route::get('packs/updateTestPacks', 'PackController@updateTestPacks')->name('packs.updateTestPacks');
    Route::get('packs/removeOffers/{id}', 'PackController@removeOffers')->name('packs.removeOffers');
    Route::get('packs/blockUser/{id}', 'PackController@blockUser')->name('packs.blockUser');
    Route::get('packs/removetestOffers/{from}/{to}', 'PackController@removetestOffers')->name('packs.removetestOffers');
    Route::get('packs/rm-urs', 'PackController@removeAllSeasonUsers')->name('packs.removeAllUsers');

    Route::get('packs/updateUserCars', 'PackController@updateUserCars')->name('packs.updateUserCars');

    Route::resource('packs', 'PackController');
    Route::resource('dynamic-texts', 'DynamicTextController');
    Route::resource('email-templates', 'EmailTemplateController');
    Route::resource('removed-plate-prefixes', 'RemovedPlatePrefixController');

    Route::get('plate-prefix', 'ApiConfigurationController@platePrefix')->name('platePrefix');
    Route::get('plate-prefix/{type}/{code}/edit', 'ApiConfigurationController@platePrefixEdit')->name('platePrefixEdit');
    Route::post('plate-prefix/{type}/{code}/update', 'ApiConfigurationController@platePrefixUpdate')->name('platePrefixUpdate');
    Route::resource('configuration', 'ApiConfigurationController');

    Route::any('parking-transaction/dt', 'ParkingTransactionController@datatable')->name('parking.transaction.datatable');
    Route::resource('parking-transaction', 'ParkingTransactionController');

    Route::resource('user-cars', 'UserCarController')->only('create', 'store', 'edit', 'update');

    Route::get('logs', 'AdminCommonController@getLog')->name('getLog');
    Route::any('getAllLogs', 'AdminCommonController@getAllLogs')->name('getAllLogs');

    Route::post('offers/change-status/{type}/{status}', 'OfferController@changeStatus')->name('offers.changeStatus');
    Route::get('offers/edit/{parentName}/{merchanteName}', 'OfferController@edit')->name('offers.edit');
    Route::post('offers/update/{parentName}/{merchanteName}', 'OfferController@update')->name('offers.update');
    Route::any('offers/datatable', 'OfferController@datatable')->name('offers.datatable');
    Route::get('offers/updateExistingOrder', 'OfferController@updateExistingOrder')->name('offers.updateExistingOrder');
    Route::get('offers', 'OfferController@index')->name('offers.index');
    Route::get('offers/update-existing', 'OfferController@updateExisting')->name('offers.updateExisting');

    //Programs
    Route::any('programs/datatable', 'ProgramController@datatable')->name('programs.datatable');
    Route::any('programs/{id}/slots/datatable', 'ProgramSlotController@datatable')->name('programs.slots.datatable');
    Route::get('programs/{id}/slots/export', 'ProgramSlotController@export')->name('programs.slots.export');
    Route::post('programs/{id}/slots/changeStatus', 'ProgramSlotController@changeStatus')->name('programs.slots.changeStatus');
    Route::resource('programs/{id}/slots', 'ProgramSlotController', ['as' => 'programs']);
    Route::post('programs/changeStatus', 'ProgramController@changeStatus')->name('programs.changeStatus');
    Route::resource('programs', 'ProgramController');
    Route::any('book-programs-slots/{id}', 'ProgramController@getSlots')->name('programs.slots.book');
    Route::post('book-programs-confirm', 'ProgramController@cofirmSlotBooking')->name('programs.book.confirm');
    Route::post('cancel-booking-slot', 'ProgramSlotController@cancelSlotBooking')->name('programs.booked-slot.cancel');
    Route::post('release-booking-slot', 'ProgramSlotController@releaseSlotBooking')->name('programs.booked-slot.release');
    Route::post('get-tables-by-type', 'TableController@getTablesByType')->name('tables.get.by.type');
    Route::any('program-report', 'ProgramReportController@index')->name('program.day.report');
    Route::post('program-report-details', 'ProgramReportController@show')->name('program.day.report.details');
    Route::any('program-onsite-collections', 'MajlisBookingController@onsiteIndex')->name('program.onsite.collections');
    Route::post('program-onsite-collection-details', 'MajlisBookingController@onsiteShow')->name('program.onsite.collection.details');
    Route::post('program-change-table', 'ProgramReportController@changeTable')->name('program.change.table');
    Route::post('program-change-table-store', 'ProgramReportController@storeChangedTable')->name('program.changed.table.store');
    Route::post('program-change-date', 'ProgramReportController@changeDate')->name('program.change.date');
    Route::get('program-release-slots', 'ProgramReportController@getReleaseSlots')->name('program.get.release.slots');
    Route::post('program-get-qrcodes', 'ProgramReportController@getQrcodes')->name('program.get.qrcodes');
    Route::get('find-majlis-bookings', 'MajlisBookingController@findBookings')->name('find.majlis.bookings');
    Route::post('majlis-bookings-datatable', 'MajlisBookingController@datatable')->name('majlis.bookings.datatable');
    Route::get('onsite-collections/export', 'MajlisBookingController@export')->name('program.onsite.collections.export');

    Route::get('promocode-update', 'DbUpdateController@promocode')->name('promocode');

    //Season
    Route::get('season/packs/{id}', 'SeasonController@packs')->name('season.packs');
    Route::get('season/offers/{id}', 'SeasonController@offers')->name('season.offers');
    Route::get('season/download/{id}', 'SeasonController@download')->name('season.download');
    Route::get('season/downloadOffer/{id}', 'SeasonController@downloadOffer')->name('season.downloadOffer');
    Route::any('season/packdatatable', 'SeasonController@packdatatable')->name('season.packdatatable');
    Route::any('season/datatable', 'SeasonController@datatable')->name('season.datatable');
    Route::post('season/changeStatus', 'SeasonController@changeStatus')->name('season.changeStatus');
    Route::post('season/changePackActivation', 'SeasonController@changePackActivation')->name('season.changePackActivation');
    Route::resource('season', 'SeasonController');
    Route::get('current-season', 'SeasonController@currentSeason')->name('current-season');
    Route::post('current-season-update/{id}', 'SeasonController@currentSeasonUpdate')->name('current-season-update');

    Route::any('pack-product-config/datatable', 'PackProductConfigController@datatable')->name('pack-product-config.datatable');
    Route::resource('pack-product-config', 'PackProductConfigController');

    Route::resource('fitness-season', 'FitnessSeasonsController');
    Route::any('fitness-season/dt', 'FitnessSeasonsController@datatable')->name('fitness-season.datatable');
    Route::post('fitness-season-status', 'FitnessSeasonsController@publish')->name('fitness-season.fitness-season-status');
    Route::post('post-sortable', 'FitnessSeasonsController@sortable_update')->name('fitness-season.post-sortable');
    Route::get('delete-fitness-season-image/{id}', 'FitnessSeasonsController@delete_fitness_season_image')->name('fitness-season.delete-fitness-season-image');
    Route::get('fitness-tracks/{cat}', 'FitnessTrackController@index')->name('fitness-track.index');
    Route::any('fitness-daily-tracks-dt', 'FitnessTrackController@dailyTracks')->name('fitness.daily-tracks.dt');

routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */
 Route::get('/activate', function() {
     return Redirect::to('en');
 });

Route::get('/', function() {
    return Redirect::to('en',301);
});

Route::get('testMails', ['as' => 'test-mails', 'uses' => 'Web\TestMailController@index']);
Route::get('testPass', ['as' => 'test-mails', 'uses' => 'Web\TestMailController@testPass']);

Route::get('test-exp', ['as' => 'test-mails', 'uses' => 'Web\TestMailController@export']);

Route::group(['prefix' => '{lang?}', 'middleware' => ['web', 'setlocale'], 'where' => ['lang' => 'en|ar']], function () {
    Route::get('/', 'Web\HomeController@index')->name('home');
    Route::post('check-activation-code', 'Web\HomeController@checkActivationCode')->name('check.activationCode');
    Route::post('generate-otp', 'Web\HomeController@generateOtp')->name('generateOtp');
    Route::post('get-emirates', 'Web\HomeController@getEmirates')->name('get.emirates');
    Route::post('get-plate-prefix', 'Web\HomeController@getPlatePrefix')->name('get.platePrefix');
    Route::post('activate-pack', 'Web\HomeController@activatePack')->name('pack.activate');
    Route::get('my-activated-pack/{id}', 'Web\HomeController@myActivatedPack')->name('my.activated.pack');
    Route::post('pack-offers', 'Web\HomeController@packOffers')->name('pack.offers');

    Route::get('offer-download/{id}', 'Web\HomeController@packOfferDownload')->name('pack-offer-download');
    Route::get('offer-hide/{id}', 'Web\HomeController@hideOffer')->name('hideOffer');

    Route::get('test', 'Web\HomeController@test')->name('pack.offers-test');

    Route::get('generate-qrcode', 'Web\HomeController@generateTestQrCode')->name('pack.qr-test');

    Route::post('load-popup-content', 'Web\HomeController@load_popup_content')->name('load-popup-content');
    Route::post('manage-car-detail', 'Web\HomeController@manage_car_detail')->name('manage-car-detail');

    Route::post('add-more-car', 'Web\HomeController@addMoreCar')->name('addMoreCar');


    Route::get('testSaleforce', 'Web\HomeController@testSaleforce')->name('testSaleforce');
    Route::get('testSaleforceUrl', 'Web\HomeController@testSaleforceUrl')->name('testSaleforceUrl');

});

app/Http/Controllers/Admin/EmailTemplateController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use Auth;
use URL;

class EmailTemplateController extends Controller
{
    public function __construct() {
        $this->middleware(function ($request, $next) {
            $user = Auth::guard('admin')->user();
            if ($user->hasRole('super-admin', 'admin') || $user->hasPermissionTo('email template_read', 'admin')) {
                return $next($request);
            } else {
                alert()->error('Your don\'t have permission to acces this page.', 'No Access!');
                return redirect()->route('admin.dashboard');
            }
        }, ['only' => ['index', 'profile', 'show']]);

        $this->middleware(function ($request, $next) {
            $user = Auth::guard('admin')->user();
            if ($user->hasRole('super-admin', 'admin') || $user->hasPermissionTo('email template_create', 'admin')) {
                return $next($request);
            } else {
                alert()->error('Your don\'t have permission to acces this page.', 'No Access!');
                return redirect()->route('admin.dashboard');
            }
        }, ['only' => ['create', 'store']]);

        $this->middleware(function ($request, $next) {
            $user = Auth::guard('admin')->user();
            if ($user->hasRole('super-admin', 'admin') || $user->hasPermissionTo('email template_update', 'admin')) {
                return $next($request);
            } else {
                alert()->error('Your don\'t have permission to acces this page.', 'No Access!');
                return redirect()->route('admin.dashboard');
            }
        }, ['only' => ['edit', 'update']]);

        $this->middleware(function ($request, $next) {
            $user = Auth::guard('admin')->user();
            if ($user->hasRole('super-admin', 'admin') || $user->hasPermissionTo('email template_delete', 'admin')) {
                return $next($request);
            } else {
                alert()->error('Your don\'t have permission to acces this page.', 'No Access!');
                return redirect()->route('admin.dashboard');
            }
        }, ['only' => ['destroy']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $templates = \App\Emailtemplate::all();
        return view('admin.email_templates.index', compact('templates'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.email_templates.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'type' => 'required',
            'subject_en' => 'required',
            'subject_ar' => 'required',
            'body_en' => 'required',
            'body_ar' => 'required',
        ]);
        $templates = new \App\Emailtemplate;
        $templates->type = $request->type;
        $templates->subject_en = $request->subject_en;
        $templates->subject_ar = $request->subject_ar;
        $templates->body_en = $request->body_en;
        $templates->body_ar = $request->body_ar;
        $templates->save();
        return redirect()->route('admin.email-templates.index')->with('success', 'Email template updated successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $templates =  \App\Emailtemplate::find($id);
        return view('admin.email_templates.edit', compact('templates'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            
            'subject_en' => 'required',
            'subject_ar' => 'required',
            'body_en' => 'required',
            'body_ar' => 'required',
        ]);
        $templates =  \App\Emailtemplate::find($id);
        $templates->type = $request->type;
        $templates->subject_en = $request->subject_en;
        $templates->subject_ar = $request->subject_ar;
        $templates->body_en = $request->body_en;
        $templates->body_ar = $request->body_ar;
        $templates->save();
        return redirect()->route('admin.email-templates.index')->with('success', 'Email template updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/email_templates/create.blade.php
@extends('adminlte::page')

@section('title', 'Add new')

@section('content_header')
<h1> Add new</h1>
@stop

@section('content')
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="box box-success">
            <div class="box-header">
                <div class="box-tools">
                    <a href="{{route('admin.email-templates.index')}}" class="btn btn-sm btn-default">Back</a>
                </div>
            </div>
           
            {{ Form::open(array('url' => 'admin/email-templates')) }}
            <div class="box-body">
                @include("admin.email_templates.form")
              
                <div class="form-group">
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        {{ Form::submit('Add', array('class' => 'btn btn-primary')) }}
                    </div>
                </div>
            </div>
            {{ Form::close() }}

                
        </div>
    </div>
</div>
@stop

resources/views/admin/email_templates/edit.blade.php
@extends('adminlte::page')

@section('title', 'Edit ')

@section('content_header')
<h1>Edit </h1>
@stop

@section('content')
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="box box-primary">
            <div class="box-header with-border">
                <a href="{{ route('admin.email-templates.index') }}" title="Back"><button class="btn btn-warning btn-xs"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
            </div>
            <div class="box-body">
                {{ Form::model($templates, array('route' => array('admin.email-templates.update', $templates->id), 'method' => 'PUT')) }}

                @include("admin.email_templates.form")

                {{ Form::submit('Update', array('class' => 'btn btn-primary')) }}

                {{ Form::close() }}

            </div>
        </div>
    </div>
</div>
@stop

resources/views/admin/email_templates/form.blade.php
@if(!isset($templates))
<div class="form-group {{ $errors->has('type') ? 'has-error' : '' }}">
    {{ Form::label('type', 'Type') }}
    {{ Form::text('type', null, array('class' => 'form-control', 'required'=>"required" )) }}
     {!! $errors->first('type','<p class="text-danger"><strong>:message</strong></p>') !!}
</div>
@else
<div class="form-group {{ $errors->has('type') ? 'has-error' : '' }}">
    {{ Form::label('type', 'Type') }}
    {{ Form::text('type', null, array('class' => 'form-control', "readonly")) }}
     {!! $errors->first('type','<p class="text-danger"><strong>:message</strong></p>') !!}
</div>
@endif


<div class="form-group {{ $errors->has('subject_en') ? 'has-error' : '' }}">
    {{ Form::label('subject_en', 'Subject (English)') }}
    {{ Form::text('subject_en', null, array('class' => 'form-control', 'required'=>"required")) }}
     {!! $errors->first('subject_en','<p class="text-danger"><strong>:message</strong></p>') !!}
</div>

<div class="form-group {{ $errors->has('subject_ar') ? 'has-error' : '' }}">
    {{ Form::label('subject_ar', 'Subject (Arabic)') }}
    {{ Form::text('subject_ar', null, array('class' => 'form-control', 'required'=>"required")) }}
     {!! $errors->first('subject_ar','<p class="text-danger"><strong>:message</strong></p>') !!}
</div>
  

<div class="form-group {{ $errors->has('body_en') ? 'has-error' : '' }}">
    {{ Form::label('body_en', 'Body (English)') }}
    {{ Form::textarea('body_en', null, array('class' => 'form-control', 'required'=>"required")) }}
     {!! $errors->first('body_en','<p class="text-danger"><strong>:message</strong></p>') !!}
</div>

<div class="form-group {{ $errors->has('body_ar') ? 'has-error' : '' }}">
    {{ Form::label('body_ar', 'Body (Arabic)') }}
    {{ Form::textarea('body_ar', null, array('class' => 'form-control', 'required'=>"required")) }}
     {!! $errors->first('body_ar','<p class="text-danger"><strong>:message</strong></p>') !!}
</div>

resources/views/admin/email_templates/index.blade.php
@extends('adminlte::page')

@section('title', 'Email temlates')

@section('content_header')
<h1> Email temlates</h1>
@stop

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="box box-success">
            <div class="box-header">
                <h3>&nbsp;</h3>
                <div class="box-tools">
                    {{-- <a href="{{route('admin.email-templates.create')}}" class="btn btn-sm btn-primary">Create new</a> --}}
                </div>

            </div>
            <div class="box-body">
            
                
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover" id="list-table">

                        <thead>
                            <tr>
                                <th>Type</th>
                                <th>Subject (English)</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @if(!empty($templates))
                                @foreach($templates as $text)
                                    <tr>
                                        <td>{{$text->type}}</td>
                                        <td>{!! $text->subject_en !!}</td>
                                        
                                        <td>
                                            <a href="{{route('admin.email-templates.edit', $text->id)}}" class="btn btn-sm btn-primary">Edit</a>
                                            
                                        </td>
                                    </tr>
                                @endforeach
                            @endif
                        </tbody>

                    </table>
                </div>

            </div>
        </div>
    </div>
</div>
@stop
@section("css")

<link rel="stylesheet" href="{{asset('css/bootstrap4-toggle.min.css')}}">
@stop
@section('js')
<script src="{{asset('js/bootstrap4-toggle.min.js')}}"></script>
<script type='text/javascript'>
    $(function () {
        
        oTable = $('#list-table').DataTable({
            ordering: false,
            serverSide: false,
            
        });
        
    });

</script>    
@stop